### ISSUE TITLE
Missing stopwords.txt

### ISSUE THREAD

**Issue by BigFishMaster** [henryhungle/MTN#3]
Have you run this code before releasing? There are many little bugs ...

**Comment by henryhungle** [comment]
Refer to #2 on stopwords.txt. 

Please use the training and validation data from the provided download link and the test data provided in this repo for evaluating. The new released test data consists 6 references (instead of 1 at the time of writing the paper) and was probably preprocessed with stopwords, and hence, needs modification to obtain the new results.
